resolver: lts-4.2

packages:
- '.'

extra-deps:
- snap-loader-dynamic-0.10.0.3
- snap-loader-static-0.9.0.2

# Override default flag values for local packages and extra-deps
flags: {}

extra-package-dbs: []
